### ISSUE TITLE
Multiple Error When Making

### ISSUE THREAD

**Issue by h3rucutu** [munjeni/miui_sony_xperia#1]
Hi munjeni, i has been git clone your miui_sony_xperia and try to running makemiui.sh lotus but, i found some error, can you help me to solve it?? I'm running on backtrack 5 r3. Below the error on my terminal

``` javascript
root@bt:~/miui_xperia/# ./makemiui.sh lotus
PORT_ROOT       = /root/miui_xperia
ANDROID_TOP     = lotus
ANDROID_OUT     = 
PORT_PRODUCT    = Unknown
USE_ANDROID_OUT = 
ANDROID_BRANCH  = 
unzip >/dev/null stockrom.zip -d out/ZIP
>>> Install framework resources for apktool...
install framework-miui-res.apk
/root/miui_xperia/tools/apktool --quiet if /root/miui_xperia/miui/system/framework/framework-miui-res.apk
unzip >/dev/null stockrom.zip "system/framework/*.apk" -d out
install out/system/framework/framework-res.apk
<<< install framework resources completed!
>>> build out/framework-res.apk...
add miui overlay resources
/root/miui_xperia/tools/remove_redef.py >/dev/null out/framework-res
/root/miui_xperia/tools/apktool --quiet b out/framework-res out/framework-res.apk
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-sw600dp-w1280dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-w480dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-w600dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-sw600dp-w1024dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-w720dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/drawable-sw600dp-mdpi
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-sw600dp-land
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-sw600dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-w500dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-w360dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/values-h720dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/layout-sw600dp
invalid resource directory name: /root/miui_xperia/lotus/out/framework-res/res/layout-w600dp
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL1920479813694750490.tmp, -x, -S, /root/miui_xperia/lotus/out/framework-res/res, -M, /root/miui_xperia/lotus/out/framework-res/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL1920479813694750490.tmp, -x, -S, /root/miui_xperia/lotus/out/framework-res/res, -M, /root/miui_xperia/lotus/out/framework-res/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: *** [out/framework-res.apk] Error 1
Error building... stopping now!
root@bt:~/miui_xperia/#
```

I hope i can solve this problem soon, thanks

**Comment by munjeni** [comment]
It must be working! I really don;t know why you getting these error! Did you modified something or added something? Allso do "repo pull" to sync everything on your machine!

**Comment by munjeni** [comment]
Maybe java?

I have runing:
java version "1.6.0_24"
OpenJDK Runtime Environment (IcedTea6 1.11.5) (6b24-1.11.5-0ubuntu1~12.04.1)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)

**Comment by h3rucutu** [comment]
I'm so sorry about that, but now i can use from your build in your repo, UNOFFICIAL MIUI lotus

Thanks
